/*
 * JS for songList generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '0c2b18ad-30dc-4103-ae45-9fdf77d705b4';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "song_20",
    "location": "song_20.html"
}, {
    "name": "song_16",
    "location": "song_16.html"
}, {
    "name": "song_3",
    "location": "song_3.html"
}, {
    "name": "song_13",
    "location": "song_13.html"
}, {
    "name": "song_4",
    "location": "song_4.html"
}, {
    "name": "song_5",
    "location": "song_5.html"
}, {
    "name": "song_7",
    "location": "song_7.html"
}, {
    "name": "song_39",
    "location": "song_39.html"
}, {
    "name": "song_2",
    "location": "song_2.html"
}, {
    "name": "song_14",
    "location": "song_14.html"
}, {
    "name": "song_28",
    "location": "song_28.html"
}, {
    "name": "song_50",
    "location": "song_50.html"
}, {
    "name": "song_17",
    "location": "song_17.html"
}, {
    "name": "song_48",
    "location": "song_48.html"
}, {
    "name": "songList",
    "location": "songList.html"
}, {
    "name": "song_18",
    "location": "song_18.html"
}, {
    "name": "song_32",
    "location": "song_32.html"
}, {
    "name": "song_34",
    "location": "song_34.html"
}, {
    "name": "song_35",
    "location": "song_35.html"
}, {
    "name": "song_40",
    "location": "song_40.html"
}, {
    "name": "song_46",
    "location": "song_46.html"
}, {
    "name": "song_21",
    "location": "song_21.html"
}, {
    "name": "song_11",
    "location": "song_11.html"
}, {
    "name": "song_27",
    "location": "song_27.html"
}, {
    "name": "song_29",
    "location": "song_29.html"
}, {
    "name": "song_33",
    "location": "song_33.html"
}, {
    "name": "song_31",
    "location": "song_31.html"
}, {
    "name": "song_19",
    "location": "song_19.html"
}, {
    "name": "song_36",
    "location": "song_36.html"
}, {
    "name": "song_47",
    "location": "song_47.html"
}, {
    "name": "song_30",
    "location": "song_30.html"
}, {
    "name": "song_45",
    "location": "song_45.html"
}, {
    "name": "song_26",
    "location": "song_26.html"
}, {
    "name": "song_25",
    "location": "song_25.html"
}, {
    "name": "song_9",
    "location": "song_9.html"
}, {
    "name": "song_8",
    "location": "song_8.html"
}, {
    "name": "song_10",
    "location": "song_10.html"
}, {
    "name": "song_22",
    "location": "song_22.html"
}, {
    "name": "song_24",
    "location": "song_24.html"
}, {
    "name": "song_37",
    "location": "song_37.html"
}, {
    "name": "song_23",
    "location": "song_23.html"
}, {
    "name": "song_15",
    "location": "song_15.html"
}, {
    "name": "song_42",
    "location": "song_42.html"
}, {
    "name": "song_1",
    "location": "song_1.html"
}, {
    "name": "song_44",
    "location": "song_44.html"
}, {
    "name": "song_41",
    "location": "song_41.html"
}, {
    "name": "song_12",
    "location": "song_12.html"
}, {
    "name": "song_6",
    "location": "song_6.html"
}, {
    "name": "song_43",
    "location": "song_43.html"
}, {
    "name": "song_51",
    "location": "song_51.html"
}, {
    "name": "song_38",
    "location": "song_38.html"
}, {
    "name": "song_49",
    "location": "song_49.html"
}, {
    "name": "song_67",
    "location": "song_67.html"
}, {
    "name": "song_65",
    "location": "song_65.html"
}, {
    "name": "song_73",
    "location": "song_73.html"
}, {
    "name": "song_71",
    "location": "song_71.html"
}, {
    "name": "song_66",
    "location": "song_66.html"
}, {
    "name": "song_64",
    "location": "song_64.html"
}, {
    "name": "song_69",
    "location": "song_69.html"
}, {
    "name": "song_79",
    "location": "song_79.html"
}, {
    "name": "song_55",
    "location": "song_55.html"
}, {
    "name": "song_84",
    "location": "song_84.html"
}, {
    "name": "song_90",
    "location": "song_90.html"
}, {
    "name": "song_82",
    "location": "song_82.html"
}, {
    "name": "song_85",
    "location": "song_85.html"
}, {
    "name": "song_86",
    "location": "song_86.html"
}, {
    "name": "song_61",
    "location": "song_61.html"
}, {
    "name": "song_87",
    "location": "song_87.html"
}, {
    "name": "song_92",
    "location": "song_92.html"
}, {
    "name": "song_62",
    "location": "song_62.html"
}, {
    "name": "song_83",
    "location": "song_83.html"
}, {
    "name": "song_81",
    "location": "song_81.html"
}, {
    "name": "song_91",
    "location": "song_91.html"
}, {
    "name": "song_88",
    "location": "song_88.html"
}, {
    "name": "song_89",
    "location": "song_89.html"
}, {
    "name": "song_93",
    "location": "song_93.html"
}, {
    "name": "song_94",
    "location": "song_94.html"
}, {
    "name": "song_95",
    "location": "song_95.html"
}, {
    "name": "song_98",
    "location": "song_98.html"
}, {
    "name": "song_103",
    "location": "song_103.html"
}, {
    "name": "song_63",
    "location": "song_63.html"
}, {
    "name": "song_72",
    "location": "song_72.html"
}, {
    "name": "song_75",
    "location": "song_75.html"
}, {
    "name": "song_60",
    "location": "song_60.html"
}, {
    "name": "song_74",
    "location": "song_74.html"
}, {
    "name": "song_59",
    "location": "song_59.html"
}, {
    "name": "song_76",
    "location": "song_76.html"
}, {
    "name": "song_77",
    "location": "song_77.html"
}, {
    "name": "song_78",
    "location": "song_78.html"
}, {
    "name": "song_52",
    "location": "song_52.html"
}, {
    "name": "song_54",
    "location": "song_54.html"
}, {
    "name": "song_68",
    "location": "song_68.html"
}, {
    "name": "song_80",
    "location": "song_80.html"
}, {
    "name": "song_70",
    "location": "song_70.html"
}, {
    "name": "song_53",
    "location": "song_53.html"
}, {
    "name": "song_56",
    "location": "song_56.html"
}, {
    "name": "song_57",
    "location": "song_57.html"
}, {
    "name": "song_58",
    "location": "song_58.html"
}, {
    "name": "song_137",
    "location": "song_137.html"
}, {
    "name": "song_138",
    "location": "song_138.html"
}, {
    "name": "song_139",
    "location": "song_139.html"
}, {
    "name": "song_140",
    "location": "song_140.html"
}, {
    "name": "song_99",
    "location": "song_99.html"
}, {
    "name": "song_109",
    "location": "song_109.html"
}, {
    "name": "song_101",
    "location": "song_101.html"
}, {
    "name": "song_107",
    "location": "song_107.html"
}, {
    "name": "song_106",
    "location": "song_106.html"
}, {
    "name": "song_111",
    "location": "song_111.html"
}, {
    "name": "song_112",
    "location": "song_112.html"
}, {
    "name": "song_105",
    "location": "song_105.html"
}, {
    "name": "song_116",
    "location": "song_116.html"
}, {
    "name": "song_108",
    "location": "song_108.html"
}, {
    "name": "song_118",
    "location": "song_118.html"
}, {
    "name": "song_119",
    "location": "song_119.html"
}, {
    "name": "song_123",
    "location": "song_123.html"
}, {
    "name": "song_122",
    "location": "song_122.html"
}, {
    "name": "song_128",
    "location": "song_128.html"
}, {
    "name": "song_136",
    "location": "song_136.html"
}, {
    "name": "song_125",
    "location": "song_125.html"
}, {
    "name": "song_134",
    "location": "song_134.html"
}, {
    "name": "song_130",
    "location": "song_130.html"
}, {
    "name": "song_126",
    "location": "song_126.html"
}, {
    "name": "song_120",
    "location": "song_120.html"
}, {
    "name": "song_124",
    "location": "song_124.html"
}, {
    "name": "song_97",
    "location": "song_97.html"
}, {
    "name": "song_110",
    "location": "song_110.html"
}, {
    "name": "song_131",
    "location": "song_131.html"
}, {
    "name": "song_121",
    "location": "song_121.html"
}, {
    "name": "song_133",
    "location": "song_133.html"
}, {
    "name": "song_127",
    "location": "song_127.html"
}, {
    "name": "song_129",
    "location": "song_129.html"
}, {
    "name": "song_113",
    "location": "song_113.html"
}, {
    "name": "song_132",
    "location": "song_132.html"
}, {
    "name": "song_117",
    "location": "song_117.html"
}, {
    "name": "song_135",
    "location": "song_135.html"
}, {
    "name": "song_102",
    "location": "song_102.html"
}, {
    "name": "song_115",
    "location": "song_115.html"
}, {
    "name": "song_100",
    "location": "song_100.html"
}, {
    "name": "song_114",
    "location": "song_114.html"
}, {
    "name": "song_96",
    "location": "song_96.html"
}, {
    "name": "song_104",
    "location": "song_104.html"
}];

function songList_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'songs': 'songList_songs',
        'mobilelistitem_1': 'songList_mobilelistitem_1',
        'mobilelistitembutton_4': 'songList_mobilelistitembutton_4',
        'mobilelistitem_2': 'songList_mobilelistitem_2',
        'mobilelistitembutton_6': 'songList_mobilelistitembutton_6',
        'mobilelistitem_3': 'songList_mobilelistitem_3',
        'mobilelistitembutton_8': 'songList_mobilelistitembutton_8',
        'mobilelistitem_4': 'songList_mobilelistitem_4',
        'mobilelistitembutton_16': 'songList_mobilelistitembutton_16',
        'mobilelistitem_5': 'songList_mobilelistitem_5',
        'mobilelistitembutton_18': 'songList_mobilelistitembutton_18',
        'mobilelistitem_6': 'songList_mobilelistitem_6',
        'mobilelistitembutton_20': 'songList_mobilelistitembutton_20',
        'mobilelistitem_7': 'songList_mobilelistitem_7',
        'mobilelistitembutton_22': 'songList_mobilelistitembutton_22',
        'mobilelistitem_8': 'songList_mobilelistitem_8',
        'mobilelistitembutton_24': 'songList_mobilelistitembutton_24',
        'mobilelistitem_9': 'songList_mobilelistitem_9',
        'mobilelistitembutton_26': 'songList_mobilelistitembutton_26',
        'mobilelistitem_10': 'songList_mobilelistitem_10',
        'mobilelistitembutton_28': 'songList_mobilelistitembutton_28',
        'mobilelistitem_11': 'songList_mobilelistitem_11',
        'mobilelistitembutton_30': 'songList_mobilelistitembutton_30',
        'mobilelistitem_12': 'songList_mobilelistitem_12',
        'mobilelistitembutton_32': 'songList_mobilelistitembutton_32',
        'mobilelistitem_13': 'songList_mobilelistitem_13',
        'mobilelistitembutton_34': 'songList_mobilelistitembutton_34',
        'mobilelistitem_14': 'songList_mobilelistitem_14',
        'mobilelistitembutton_36': 'songList_mobilelistitembutton_36',
        'mobilelistitem_15': 'songList_mobilelistitem_15',
        'mobilelistitembutton_38': 'songList_mobilelistitembutton_38',
        'mobilelistitem_16': 'songList_mobilelistitem_16',
        'mobilelistitembutton_40': 'songList_mobilelistitembutton_40',
        'mobilelistitem_17': 'songList_mobilelistitem_17',
        'mobilelistitembutton_42': 'songList_mobilelistitembutton_42',
        'mobilelistitem_18': 'songList_mobilelistitem_18',
        'mobilelistitembutton_44': 'songList_mobilelistitembutton_44',
        'mobilelistitem_19': 'songList_mobilelistitem_19',
        'mobilelistitembutton_46': 'songList_mobilelistitembutton_46',
        'mobilelistitem_20': 'songList_mobilelistitem_20',
        'mobilelistitembutton_48': 'songList_mobilelistitembutton_48',
        'mobilelistitem_21': 'songList_mobilelistitem_21',
        'mobilelistitembutton_55': 'songList_mobilelistitembutton_55',
        'mobilelistitem_22': 'songList_mobilelistitem_22',
        'mobilelistitembutton_57': 'songList_mobilelistitembutton_57',
        'mobilelistitem_23': 'songList_mobilelistitem_23',
        'mobilelistitembutton_59': 'songList_mobilelistitembutton_59',
        'mobilelistitem_24': 'songList_mobilelistitem_24',
        'mobilelistitembutton_61': 'songList_mobilelistitembutton_61',
        'mobilelistitem_25': 'songList_mobilelistitem_25',
        'mobilelistitembutton_63': 'songList_mobilelistitembutton_63',
        'mobilelistitem_26': 'songList_mobilelistitem_26',
        'mobilelistitembutton_65': 'songList_mobilelistitembutton_65',
        'mobilelistitem_27': 'songList_mobilelistitem_27',
        'mobilelistitembutton_67': 'songList_mobilelistitembutton_67',
        'mobilelistitem_28': 'songList_mobilelistitem_28',
        'mobilelistitembutton_69': 'songList_mobilelistitembutton_69',
        'mobilelistitem_29': 'songList_mobilelistitem_29',
        'mobilelistitembutton_71': 'songList_mobilelistitembutton_71',
        'mobilelistitem_30': 'songList_mobilelistitem_30',
        'mobilelistitembutton_73': 'songList_mobilelistitembutton_73',
        'mobilelistitem_31': 'songList_mobilelistitem_31',
        'mobilelistitembutton_75': 'songList_mobilelistitembutton_75',
        'mobilelistitem_32': 'songList_mobilelistitem_32',
        'mobilelistitembutton_77': 'songList_mobilelistitembutton_77',
        'mobilelistitem_33': 'songList_mobilelistitem_33',
        'mobilelistitembutton_79': 'songList_mobilelistitembutton_79',
        'mobilelistitem_34': 'songList_mobilelistitem_34',
        'mobilelistitembutton_81': 'songList_mobilelistitembutton_81',
        'mobilelistitem_35': 'songList_mobilelistitem_35',
        'mobilelistitembutton_83': 'songList_mobilelistitembutton_83',
        'mobilelistitem_36': 'songList_mobilelistitem_36',
        'mobilelistitembutton_85': 'songList_mobilelistitembutton_85',
        'mobilelistitem_37': 'songList_mobilelistitem_37',
        'mobilelistitembutton_87': 'songList_mobilelistitembutton_87',
        'mobilelistitem_38': 'songList_mobilelistitem_38',
        'mobilelistitembutton_89': 'songList_mobilelistitembutton_89',
        'mobilelistitem_39': 'songList_mobilelistitem_39',
        'mobilelistitembutton_91': 'songList_mobilelistitembutton_91',
        'mobilelistitem_40': 'songList_mobilelistitem_40',
        'mobilelistitembutton_93': 'songList_mobilelistitembutton_93',
        'mobilelistitem_41': 'songList_mobilelistitem_41',
        'mobilelistitembutton_95': 'songList_mobilelistitembutton_95',
        'mobilelistitem_42': 'songList_mobilelistitem_42',
        'mobilelistitembutton_97': 'songList_mobilelistitembutton_97',
        'mobilelistitem_43': 'songList_mobilelistitem_43',
        'mobilelistitembutton_99': 'songList_mobilelistitembutton_99',
        'mobilelistitem_44': 'songList_mobilelistitem_44',
        'mobilelistitembutton_101': 'songList_mobilelistitembutton_101',
        'mobilelistitem_45': 'songList_mobilelistitem_45',
        'mobilelistitembutton_103': 'songList_mobilelistitembutton_103',
        'mobilelistitem_46': 'songList_mobilelistitem_46',
        'mobilelistitembutton_105': 'songList_mobilelistitembutton_105',
        'mobilelistitem_47': 'songList_mobilelistitem_47',
        'mobilelistitembutton_107': 'songList_mobilelistitembutton_107',
        'mobilelistitem_48': 'songList_mobilelistitem_48',
        'mobilelistitembutton_109': 'songList_mobilelistitembutton_109',
        'mobilelistitem_49': 'songList_mobilelistitem_49',
        'mobilelistitembutton_111': 'songList_mobilelistitembutton_111',
        'mobilelistitem_50': 'songList_mobilelistitem_50',
        'mobilelistitembutton_113': 'songList_mobilelistitembutton_113',
        'mobilelistitem_51': 'songList_mobilelistitem_51',
        'mobilelistitembutton_115': 'songList_mobilelistitembutton_115',
        'mobilelistitem_52': 'songList_mobilelistitem_52',
        'mobilelistitembutton_117': 'songList_mobilelistitembutton_117',
        'mobilelistitem_53': 'songList_mobilelistitem_53',
        'mobilelistitembutton_119': 'songList_mobilelistitembutton_119',
        'mobilelistitem_54': 'songList_mobilelistitem_54',
        'mobilelistitembutton_121': 'songList_mobilelistitembutton_121',
        'mobilelistitem_55': 'songList_mobilelistitem_55',
        'mobilelistitembutton_123': 'songList_mobilelistitembutton_123',
        'mobilelistitem_56': 'songList_mobilelistitem_56',
        'mobilelistitembutton_125': 'songList_mobilelistitembutton_125',
        'mobilelistitem_57': 'songList_mobilelistitem_57',
        'mobilelistitembutton_127': 'songList_mobilelistitembutton_127',
        'mobilelistitem_58': 'songList_mobilelistitem_58',
        'mobilelistitembutton_129': 'songList_mobilelistitembutton_129',
        'mobilelistitem_59': 'songList_mobilelistitem_59',
        'mobilelistitembutton_131': 'songList_mobilelistitembutton_131',
        'mobilelistitem_60': 'songList_mobilelistitem_60',
        'mobilelistitembutton_133': 'songList_mobilelistitembutton_133',
        'mobilelistitem_61': 'songList_mobilelistitem_61',
        'mobilelistitembutton_135': 'songList_mobilelistitembutton_135',
        'mobilelistitem_62': 'songList_mobilelistitem_62',
        'mobilelistitembutton_137': 'songList_mobilelistitembutton_137',
        'mobilelistitem_63': 'songList_mobilelistitem_63',
        'mobilelistitem_64': 'songList_mobilelistitem_64',
        'mobilelistitembutton_141': 'songList_mobilelistitembutton_141',
        'mobilelistitem_65': 'songList_mobilelistitem_65',
        'mobilelistitembutton_143': 'songList_mobilelistitembutton_143',
        'mobilelistitem_66': 'songList_mobilelistitem_66',
        'mobilelistitembutton_145': 'songList_mobilelistitembutton_145',
        'mobilelistitem_67': 'songList_mobilelistitem_67',
        'mobilelistitembutton_147': 'songList_mobilelistitembutton_147',
        'mobilelistitem_68': 'songList_mobilelistitem_68',
        'mobilelistitembutton_149': 'songList_mobilelistitembutton_149',
        'mobilelistitem_69': 'songList_mobilelistitem_69',
        'mobilelistitembutton_151': 'songList_mobilelistitembutton_151',
        'mobilelistitem_70': 'songList_mobilelistitem_70',
        'mobilelistitembutton_153': 'songList_mobilelistitembutton_153',
        'mobilelistitem_71': 'songList_mobilelistitem_71',
        'mobilelistitembutton_155': 'songList_mobilelistitembutton_155',
        'mobilelistitem_72': 'songList_mobilelistitem_72',
        'mobilelistitembutton_157': 'songList_mobilelistitembutton_157',
        'mobilelistitem_73': 'songList_mobilelistitem_73',
        'mobilelistitembutton_159': 'songList_mobilelistitembutton_159',
        'mobilelistitem_74': 'songList_mobilelistitem_74',
        'mobilelistitembutton_161': 'songList_mobilelistitembutton_161',
        'mobilelistitem_75': 'songList_mobilelistitem_75',
        'mobilelistitembutton_163': 'songList_mobilelistitembutton_163',
        'mobilelistitem_76': 'songList_mobilelistitem_76',
        'mobilelistitembutton_165': 'songList_mobilelistitembutton_165',
        'mobilelistitem_77': 'songList_mobilelistitem_77',
        'mobilelistitembutton_167': 'songList_mobilelistitembutton_167',
        'mobilelistitem_78': 'songList_mobilelistitem_78',
        'mobilelistitembutton_169': 'songList_mobilelistitembutton_169',
        'mobilelistitem_79': 'songList_mobilelistitem_79',
        'mobilelistitembutton_171': 'songList_mobilelistitembutton_171',
        'mobilelistitem_80': 'songList_mobilelistitem_80',
        'mobilelistitembutton_173': 'songList_mobilelistitembutton_173',
        'mobilelistitem_81': 'songList_mobilelistitem_81',
        'mobilelistitembutton_175': 'songList_mobilelistitembutton_175',
        'mobilelistitem_82': 'songList_mobilelistitem_82',
        'mobilelistitembutton_177': 'songList_mobilelistitembutton_177',
        'mobilelistitem_83': 'songList_mobilelistitem_83',
        'mobilelistitembutton_179': 'songList_mobilelistitembutton_179',
        'mobilelistitem_84': 'songList_mobilelistitem_84',
        'mobilelistitembutton_181': 'songList_mobilelistitembutton_181',
        'mobilelistitem_85': 'songList_mobilelistitem_85',
        'mobilelistitembutton_183': 'songList_mobilelistitembutton_183',
        'mobilelistitem_86': 'songList_mobilelistitem_86',
        'mobilelistitembutton_185': 'songList_mobilelistitembutton_185',
        'mobilelistitem_87': 'songList_mobilelistitem_87',
        'mobilelistitembutton_187': 'songList_mobilelistitembutton_187',
        'mobilelistitem_88': 'songList_mobilelistitem_88',
        'mobilelistitembutton_189': 'songList_mobilelistitembutton_189',
        'mobilelistitem_89': 'songList_mobilelistitem_89',
        'mobilelistitembutton_191': 'songList_mobilelistitembutton_191',
        'mobilelistitem_90': 'songList_mobilelistitem_90',
        'mobilelistitembutton_193': 'songList_mobilelistitembutton_193',
        'mobilelistitem_91': 'songList_mobilelistitem_91',
        'mobilelistitembutton_195': 'songList_mobilelistitembutton_195',
        'mobilelistitem_92': 'songList_mobilelistitem_92',
        'mobilelistitembutton_197': 'songList_mobilelistitembutton_197',
        'mobilelistitem_93': 'songList_mobilelistitem_93',
        'mobilelistitembutton_199': 'songList_mobilelistitembutton_199',
        'mobilelistitem_94': 'songList_mobilelistitem_94',
        'mobilelistitembutton_201': 'songList_mobilelistitembutton_201',
        'mobilelistitem_95': 'songList_mobilelistitem_95',
        'mobilelistitembutton_203': 'songList_mobilelistitembutton_203',
        'mobilelistitem_96': 'songList_mobilelistitem_96',
        'mobilelistitembutton_205': 'songList_mobilelistitembutton_205',
        'mobilelistitem_97': 'songList_mobilelistitem_97',
        'mobilelistitembutton_207': 'songList_mobilelistitembutton_207',
        'mobilelistitem_98': 'songList_mobilelistitem_98',
        'mobilelistitembutton_209': 'songList_mobilelistitembutton_209',
        'mobilelistitem_99': 'songList_mobilelistitem_99',
        'mobilelistitembutton_211': 'songList_mobilelistitembutton_211',
        'mobilelistitem_100': 'songList_mobilelistitem_100',
        'mobilelistitembutton_213': 'songList_mobilelistitembutton_213',
        'mobilelistitem_101': 'songList_mobilelistitem_101',
        'mobilelistitembutton_215': 'songList_mobilelistitembutton_215',
        'mobilelistitem_102': 'songList_mobilelistitem_102',
        'mobilelistitembutton_217': 'songList_mobilelistitembutton_217',
        'mobilelistitem_103': 'songList_mobilelistitem_103',
        'mobilelistitembutton_219': 'songList_mobilelistitembutton_219',
        'mobilelistitem_104': 'songList_mobilelistitem_104',
        'mobilelistitembutton_221': 'songList_mobilelistitembutton_221',
        'mobilelistitem_105': 'songList_mobilelistitem_105',
        'mobilelistitembutton_223': 'songList_mobilelistitembutton_223',
        'mobilelistitem_106': 'songList_mobilelistitem_106',
        'mobilelistitembutton_225': 'songList_mobilelistitembutton_225',
        'mobilelistitem_107': 'songList_mobilelistitem_107',
        'mobilelistitembutton_227': 'songList_mobilelistitembutton_227',
        'mobilelistitem_108': 'songList_mobilelistitem_108',
        'mobilelistitembutton_229': 'songList_mobilelistitembutton_229',
        'mobilelistitem_109': 'songList_mobilelistitem_109',
        'mobilelistitembutton_231': 'songList_mobilelistitembutton_231',
        'mobilelistitem_110': 'songList_mobilelistitem_110',
        'mobilelistitembutton_233': 'songList_mobilelistitembutton_233',
        'mobilelistitem_111': 'songList_mobilelistitem_111',
        'mobilelistitembutton_235': 'songList_mobilelistitembutton_235',
        'mobilelistitem_112': 'songList_mobilelistitem_112',
        'mobilelistitembutton_237': 'songList_mobilelistitembutton_237',
        'mobilelistitem_113': 'songList_mobilelistitem_113',
        'mobilelistitembutton_239': 'songList_mobilelistitembutton_239',
        'mobilelistitem_114': 'songList_mobilelistitem_114',
        'mobilelistitembutton_241': 'songList_mobilelistitembutton_241',
        'mobilelistitem_115': 'songList_mobilelistitem_115',
        'mobilelistitembutton_243': 'songList_mobilelistitembutton_243',
        'mobilelistitem_116': 'songList_mobilelistitem_116',
        'mobilelistitembutton_245': 'songList_mobilelistitembutton_245',
        'mobilelistitem_117': 'songList_mobilelistitem_117',
        'mobilelistitembutton_247': 'songList_mobilelistitembutton_247',
        'mobilelistitem_118': 'songList_mobilelistitem_118',
        'mobilelistitembutton_249': 'songList_mobilelistitembutton_249',
        'mobilelistitem_119': 'songList_mobilelistitem_119',
        'mobilelistitembutton_251': 'songList_mobilelistitembutton_251',
        'mobilelistitem_120': 'songList_mobilelistitem_120',
        'mobilelistitembutton_253': 'songList_mobilelistitembutton_253',
        'mobilelistitem_121': 'songList_mobilelistitem_121',
        'mobilelistitembutton_255': 'songList_mobilelistitembutton_255',
        'mobilelistitem_122': 'songList_mobilelistitem_122',
        'mobilelistitembutton_257': 'songList_mobilelistitembutton_257',
        'mobilelistitem_123': 'songList_mobilelistitem_123',
        'mobilelistitembutton_259': 'songList_mobilelistitembutton_259',
        'mobilelistitem_124': 'songList_mobilelistitem_124',
        'mobilelistitembutton_261': 'songList_mobilelistitembutton_261',
        'mobilelistitem_125': 'songList_mobilelistitem_125',
        'mobilelistitembutton_263': 'songList_mobilelistitembutton_263',
        'mobilelistitem_126': 'songList_mobilelistitem_126',
        'mobilelistitembutton_265': 'songList_mobilelistitembutton_265',
        'mobilelistitem_127': 'songList_mobilelistitem_127',
        'mobilelistitembutton_267': 'songList_mobilelistitembutton_267',
        'mobilelistitem_128': 'songList_mobilelistitem_128',
        'mobilelistitembutton_269': 'songList_mobilelistitembutton_269',
        'mobilelistitem_129': 'songList_mobilelistitem_129',
        'mobilelistitembutton_271': 'songList_mobilelistitembutton_271',
        'mobilelistitem_130': 'songList_mobilelistitem_130',
        'mobilelistitembutton_273': 'songList_mobilelistitembutton_273',
        'mobilelistitem_131': 'songList_mobilelistitem_131',
        'mobilelistitembutton_275': 'songList_mobilelistitembutton_275',
        'mobilelistitem_132': 'songList_mobilelistitem_132',
        'mobilelistitembutton_277': 'songList_mobilelistitembutton_277',
        'mobilelistitem_133': 'songList_mobilelistitem_133',
        'mobilelistitembutton_279': 'songList_mobilelistitembutton_279',
        'mobilelistitem_134': 'songList_mobilelistitem_134',
        'mobilelistitembutton_281': 'songList_mobilelistitembutton_281',
        'mobilelistitem_135': 'songList_mobilelistitem_135',
        'mobilelistitembutton_283': 'songList_mobilelistitembutton_283',
        'mobilelistitem_136': 'songList_mobilelistitem_136',
        'mobilelistitembutton_285': 'songList_mobilelistitembutton_285',
        'mobilelistitem_137': 'songList_mobilelistitem_137',
        'mobilelistitembutton_287': 'songList_mobilelistitembutton_287',
        'mobilelistitem_138': 'songList_mobilelistitem_138',
        'mobilelistitembutton_138': 'songList_mobilelistitembutton_138',
        'mobilelistitem_139': 'songList_mobilelistitem_139',
        'mobilelistitembutton_139': 'songList_mobilelistitembutton_139',
        'mobilelistitem_140': 'songList_mobilelistitem_140',
        'mobilelistitembutton_140': 'songList_mobilelistitembutton_140'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'songList';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var songList_onLoad = function() {
        songList_elementsExtraJS();
        songList_deviceEvents();
        songList_windowEvents();
        songList_elementsEvents();
    };
    // screen window events
    function songList_windowEvents() {
        $('#songList').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function songList_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function songList_elementsExtraJS() {
        // screen (songList) extra code
        /* songs */
        listView = $("#songList_songs");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#songList_songs .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_1 */
        /* mobilelistitem_2 */
        /* mobilelistitem_3 */
        /* mobilelistitem_4 */
        /* mobilelistitem_5 */
        /* mobilelistitem_6 */
        /* mobilelistitem_7 */
        /* mobilelistitem_8 */
        /* mobilelistitem_9 */
        /* mobilelistitem_10 */
        /* mobilelistitem_11 */
        /* mobilelistitem_12 */
        /* mobilelistitem_13 */
        /* mobilelistitem_14 */
        /* mobilelistitem_15 */
        /* mobilelistitem_16 */
        /* mobilelistitem_17 */
        /* mobilelistitem_18 */
        /* mobilelistitem_19 */
        /* mobilelistitem_20 */
        /* mobilelistitem_21 */
        /* mobilelistitem_22 */
        /* mobilelistitem_23 */
        /* mobilelistitem_24 */
        /* mobilelistitem_25 */
        /* mobilelistitem_26 */
        /* mobilelistitem_27 */
        /* mobilelistitem_28 */
        /* mobilelistitem_29 */
        /* mobilelistitem_30 */
        /* mobilelistitem_31 */
        /* mobilelistitem_32 */
        /* mobilelistitem_33 */
        /* mobilelistitem_34 */
        /* mobilelistitem_35 */
        /* mobilelistitem_36 */
        /* mobilelistitem_37 */
        /* mobilelistitem_38 */
        /* mobilelistitem_39 */
        /* mobilelistitem_40 */
        /* mobilelistitem_41 */
        /* mobilelistitem_42 */
        /* mobilelistitem_43 */
        /* mobilelistitem_44 */
        /* mobilelistitem_45 */
        /* mobilelistitem_46 */
        /* mobilelistitem_47 */
        /* mobilelistitem_48 */
        /* mobilelistitem_49 */
        /* mobilelistitem_50 */
        /* mobilelistitem_51 */
        /* mobilelistitem_52 */
        /* mobilelistitem_53 */
        /* mobilelistitem_54 */
        /* mobilelistitem_55 */
        /* mobilelistitem_56 */
        /* mobilelistitem_57 */
        /* mobilelistitem_58 */
        /* mobilelistitem_59 */
        /* mobilelistitem_60 */
        /* mobilelistitem_61 */
        /* mobilelistitem_62 */
        /* mobilelistitem_63 */
        /* mobilelistitem_64 */
        /* mobilelistitem_65 */
        /* mobilelistitem_66 */
        /* mobilelistitem_67 */
        /* mobilelistitem_68 */
        /* mobilelistitem_69 */
        /* mobilelistitem_70 */
        /* mobilelistitem_71 */
        /* mobilelistitem_72 */
        /* mobilelistitem_73 */
        /* mobilelistitem_74 */
        /* mobilelistitem_75 */
        /* mobilelistitem_76 */
        /* mobilelistitem_77 */
        /* mobilelistitem_78 */
        /* mobilelistitem_79 */
        /* mobilelistitem_80 */
        /* mobilelistitem_81 */
        /* mobilelistitem_82 */
        /* mobilelistitem_83 */
        /* mobilelistitem_84 */
        /* mobilelistitem_85 */
        /* mobilelistitem_86 */
        /* mobilelistitem_87 */
        /* mobilelistitem_88 */
        /* mobilelistitem_89 */
        /* mobilelistitem_90 */
        /* mobilelistitem_91 */
        /* mobilelistitem_92 */
        /* mobilelistitem_93 */
        /* mobilelistitem_94 */
        /* mobilelistitem_95 */
        /* mobilelistitem_96 */
        /* mobilelistitem_97 */
        /* mobilelistitem_98 */
        /* mobilelistitem_99 */
        /* mobilelistitem_100 */
        /* mobilelistitem_101 */
        /* mobilelistitem_102 */
        /* mobilelistitem_103 */
        /* mobilelistitem_104 */
        /* mobilelistitem_105 */
        /* mobilelistitem_106 */
        /* mobilelistitem_107 */
        /* mobilelistitem_108 */
        /* mobilelistitem_109 */
        /* mobilelistitem_110 */
        /* mobilelistitem_111 */
        /* mobilelistitem_112 */
        /* mobilelistitem_113 */
        /* mobilelistitem_114 */
        /* mobilelistitem_115 */
        /* mobilelistitem_116 */
        /* mobilelistitem_117 */
        /* mobilelistitem_118 */
        /* mobilelistitem_119 */
        /* mobilelistitem_120 */
        /* mobilelistitem_121 */
        /* mobilelistitem_122 */
        /* mobilelistitem_123 */
        /* mobilelistitem_124 */
        /* mobilelistitem_125 */
        /* mobilelistitem_126 */
        /* mobilelistitem_127 */
        /* mobilelistitem_128 */
        /* mobilelistitem_129 */
        /* mobilelistitem_130 */
        /* mobilelistitem_131 */
        /* mobilelistitem_132 */
        /* mobilelistitem_133 */
        /* mobilelistitem_134 */
        /* mobilelistitem_135 */
        /* mobilelistitem_136 */
        /* mobilelistitem_137 */
        /* mobilelistitem_138 */
        /* mobilelistitem_139 */
        /* mobilelistitem_140 */
    };
    // screen elements handler
    function songList_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_1"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_1', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_1"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_2', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_2"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_3', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_3"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_4', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_4"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_5', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_5"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_7', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_6"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_6', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_7"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_8"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_8', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_8"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_9"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_9', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_9"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_10"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_10', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_10"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_11', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_11"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_12"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_12', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_12"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_13"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_13', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_13"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_14"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_14', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_14"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_15"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_15', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_15"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_16"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_16', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_16"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_17', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_17"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_18"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_18', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_18"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_19"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_19', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_19"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_20"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_20', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_20"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_21"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_21', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_21"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_22"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_22', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_22"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_23"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_23', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_23"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_24"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_24', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_24"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_25"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_25', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_25"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_26"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_26', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_26"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_27"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_27', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_27"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_28"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_28', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_28"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_29"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_29', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_29"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_30"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_30', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_30"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_31"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_31', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_31"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_32"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_32', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_32"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_33"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_33', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_33"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_34"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_34', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_34"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_35"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_35', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_35"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_36"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_36', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_36"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_37"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_37', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_37"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_38"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_38', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_38"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_39"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_39', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_39"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_40"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_40', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_40"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_41"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_41', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_41"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_42"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_42', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_42"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_43"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_43', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_43"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_44"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_44', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_44"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_45"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_45', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_45"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_46"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_46', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_46"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_47"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_47', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_47"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_48"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_48', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_48"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_49"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_49', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_49"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_50"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_50', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_50"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_51"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_51', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_51"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_52"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_52', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_52"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_53"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_53', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_53"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_54"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_54', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_54"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_55"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_54', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_55"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_56"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_56', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_56"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_57"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_57', {
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_57"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_58"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_58', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_58"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_59"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_59', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_59"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_60"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_60', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_60"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_61"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_61', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_61"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_62"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_62', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_62"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_63"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_73', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_63"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_64"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_64', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_64"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_65"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_65', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_65"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_66"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_66', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_66"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_67"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_67', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_67"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_68"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_68', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_68"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_69"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_69', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_69"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_70"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_70', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_70"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_71"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_71', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_71"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_72"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_72', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_72"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_73"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_73', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_73"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_74"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_74', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_74"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_75"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_75', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_75"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_76"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_76', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_76"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_77"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_77', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_77"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_78"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_78', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_78"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_79"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_79', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_79"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_80"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_80', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_80"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_81"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_81', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_81"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_82"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_82', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_82"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_83"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_83', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_83"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_84"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_84', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_84"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_85"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_85', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_85"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_86"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_86', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_86"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_87"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_87', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_87"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_88"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_88', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_88"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_89"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_89', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_89"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_90"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_90', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_90"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_91"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_91', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_91"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_92"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_92', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_92"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_93"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_93', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_93"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_94"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_94', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_94"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_95"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_95', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_95"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_96"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_96', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_96"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_97"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_97', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_97"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_98"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_98', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_98"]');
		$(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_99"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_99', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_99"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_100"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_100', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_100"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_101"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_101', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_101"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_102"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_102', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_102"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_103"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_103', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_103"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_104"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_104', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_104"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_105"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_105', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_105"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_106"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_106', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_106"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_107"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_107', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_107"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_108"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_108', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_108"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_109"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_109', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_109"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_110"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_110', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_110"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_111"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_111', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_111"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_112"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_112', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_112"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_113"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_113', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_113"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_114"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_114', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_114"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_115"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_115', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_115"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_116"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_116', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_116"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_117"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_117', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_117"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_118"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_118', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_118"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_119"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_119', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_119"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_120"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_120', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_120"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_121"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_121', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_121"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_122"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_122', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_122"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_123"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_123', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_123"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_124"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_124', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_124"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_125"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_125', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_125"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_126"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_126', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_126"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_127"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_127', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_127"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_128"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_128', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_128"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_129"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_129', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_129"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_130"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_130', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_130"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_131"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_131', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_131"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_132"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_132', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_132"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_133"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_133', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_133"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_134"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_134', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_134"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_135"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_135', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_135"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_136"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_136', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_136"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_137"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_137', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_137"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_138"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_138', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_138"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_139"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_139', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_139"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_140"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song_140', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_140"]');
    };
    $(document).off("pagebeforeshow", "#songList").on("pagebeforeshow", "#songList", function(event, ui) {
        Apperyio.CurrentScreen = "songList";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    songList_onLoad();
};
$(document).off("pagecreate", "#songList").on("pagecreate", "#songList", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    songList_js();
});
