/*
 * JS for songList generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '0c2b18ad-30dc-4103-ae45-9fdf77d705b4';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "song18",
    "location": "song18.html"
}, {
    "name": "song19",
    "location": "song19.html"
}, {
    "name": "song3",
    "location": "song3.html"
}, {
    "name": "song20",
    "location": "song20.html"
}, {
    "name": "song4",
    "location": "song4.html"
}, {
    "name": "song5",
    "location": "song5.html"
}, {
    "name": "song6",
    "location": "song6.html"
}, {
    "name": "song36",
    "location": "song36.html"
}, {
    "name": "song2",
    "location": "song2.html"
}, {
    "name": "song16",
    "location": "song16.html"
}, {
    "name": "song38",
    "location": "song38.html"
}, {
    "name": "song39",
    "location": "song39.html"
}, {
    "name": "song17",
    "location": "song17.html"
}, {
    "name": "song40",
    "location": "song40.html"
}, {
    "name": "songList",
    "location": "songList.html"
}, {
    "name": "song15",
    "location": "song15.html"
}, {
    "name": "song32",
    "location": "song32.html"
}, {
    "name": "song33",
    "location": "song33.html"
}, {
    "name": "song34",
    "location": "song34.html"
}, {
    "name": "song35",
    "location": "song35.html"
}, {
    "name": "song49",
    "location": "song49.html"
}, {
    "name": "song14",
    "location": "song14.html"
}, {
    "name": "song12",
    "location": "song12.html"
}, {
    "name": "song27",
    "location": "song27.html"
}, {
    "name": "song28",
    "location": "song28.html"
}, {
    "name": "song29",
    "location": "song29.html"
}, {
    "name": "song30",
    "location": "song30.html"
}, {
    "name": "song13",
    "location": "song13.html"
}, {
    "name": "song47",
    "location": "song47.html"
}, {
    "name": "song48",
    "location": "song48.html"
}, {
    "name": "song31",
    "location": "song31.html"
}, {
    "name": "song45",
    "location": "song45.html"
}, {
    "name": "song22",
    "location": "song22.html"
}, {
    "name": "song23",
    "location": "song23.html"
}, {
    "name": "song9",
    "location": "song9.html"
}, {
    "name": "song10",
    "location": "song10.html"
}, {
    "name": "song11",
    "location": "song11.html"
}, {
    "name": "song24",
    "location": "song24.html"
}, {
    "name": "song25",
    "location": "song25.html"
}, {
    "name": "song46",
    "location": "song46.html"
}, {
    "name": "song26",
    "location": "song26.html"
}, {
    "name": "song21",
    "location": "song21.html"
}, {
    "name": "song37",
    "location": "song37.html"
}, {
    "name": "song1",
    "location": "song1.html"
}, {
    "name": "song43",
    "location": "song43.html"
}, {
    "name": "song44",
    "location": "song44.html"
}, {
    "name": "song8",
    "location": "song8.html"
}, {
    "name": "song7",
    "location": "song7.html"
}, {
    "name": "song41",
    "location": "song41.html"
}, {
    "name": "song42",
    "location": "song42.html"
}, {
    "name": "song50",
    "location": "song50.html"
}, {
    "name": "song51",
    "location": "song51.html"
}, {
    "name": "song68",
    "location": "song68.html"
}, {
    "name": "song62",
    "location": "song62.html"
}, {
    "name": "song63",
    "location": "song63.html"
}, {
    "name": "song64",
    "location": "song64.html"
}, {
    "name": "song65",
    "location": "song65.html"
}, {
    "name": "song66",
    "location": "song66.html"
}, {
    "name": "song67",
    "location": "song67.html"
}, {
    "name": "song79",
    "location": "song79.html"
}, {
    "name": "song80",
    "location": "song80.html"
}, {
    "name": "song82",
    "location": "song82.html"
}, {
    "name": "song83",
    "location": "song83.html"
}, {
    "name": "song84",
    "location": "song84.html"
}, {
    "name": "song85",
    "location": "song85.html"
}, {
    "name": "song86",
    "location": "song86.html"
}, {
    "name": "song60",
    "location": "song60.html"
}, {
    "name": "song87",
    "location": "song87.html"
}, {
    "name": "song88",
    "location": "song88.html"
}, {
    "name": "song61",
    "location": "song61.html"
}, {
    "name": "song89",
    "location": "song89.html"
}, {
    "name": "song90",
    "location": "song90.html"
}, {
    "name": "song91",
    "location": "song91.html"
}, {
    "name": "song92",
    "location": "song92.html"
}, {
    "name": "song93",
    "location": "song93.html"
}, {
    "name": "song94",
    "location": "song94.html"
}, {
    "name": "song95",
    "location": "song95.html"
}, {
    "name": "song96",
    "location": "song96.html"
}, {
    "name": "song97",
    "location": "song97.html"
}, {
    "name": "song98",
    "location": "song98.html"
}, {
    "name": "song71",
    "location": "song71.html"
}, {
    "name": "song72",
    "location": "song72.html"
}, {
    "name": "song73",
    "location": "song73.html"
}, {
    "name": "song74",
    "location": "song74.html"
}, {
    "name": "song58",
    "location": "song58.html"
}, {
    "name": "song75",
    "location": "song75.html"
}, {
    "name": "song59",
    "location": "song59.html"
}, {
    "name": "song76",
    "location": "song76.html"
}, {
    "name": "song77",
    "location": "song77.html"
}, {
    "name": "song78",
    "location": "song78.html"
}, {
    "name": "song56",
    "location": "song56.html"
}, {
    "name": "song57",
    "location": "song57.html"
}, {
    "name": "song70",
    "location": "song70.html"
}, {
    "name": "song81",
    "location": "song81.html"
}, {
    "name": "song69",
    "location": "song69.html"
}, {
    "name": "song52",
    "location": "song52.html"
}, {
    "name": "song53",
    "location": "song53.html"
}, {
    "name": "song54",
    "location": "song54.html"
}, {
    "name": "song55",
    "location": "song55.html"
}, {
    "name": "song136",
    "location": "song136.html"
}, {
    "name": "song99",
    "location": "song99.html"
}, {
    "name": "song115",
    "location": "song115.html"
}, {
    "name": "song104",
    "location": "song104.html"
}, {
    "name": "song105",
    "location": "song105.html"
}, {
    "name": "song116",
    "location": "song116.html"
}, {
    "name": "song117",
    "location": "song117.html"
}, {
    "name": "song106",
    "location": "song106.html"
}, {
    "name": "song107",
    "location": "song107.html"
}, {
    "name": "song118",
    "location": "song118.html"
}, {
    "name": "song108",
    "location": "song108.html"
}, {
    "name": "song119",
    "location": "song119.html"
}, {
    "name": "song120",
    "location": "song120.html"
}, {
    "name": "song121",
    "location": "song121.html"
}, {
    "name": "song123",
    "location": "song123.html"
}, {
    "name": "song124",
    "location": "song124.html"
}, {
    "name": "song137",
    "location": "song137.html"
}, {
    "name": "song125",
    "location": "song125.html"
}, {
    "name": "song138",
    "location": "song138.html"
}, {
    "name": "song126",
    "location": "song126.html"
}, {
    "name": "song127",
    "location": "song127.html"
}, {
    "name": "song128",
    "location": "song128.html"
}, {
    "name": "song129",
    "location": "song129.html"
}, {
    "name": "song100",
    "location": "song100.html"
}, {
    "name": "song111",
    "location": "song111.html"
}, {
    "name": "song122",
    "location": "song122.html"
}, {
    "name": "song130",
    "location": "song130.html"
}, {
    "name": "song131",
    "location": "song131.html"
}, {
    "name": "song132",
    "location": "song132.html"
}, {
    "name": "song133",
    "location": "song133.html"
}, {
    "name": "song109",
    "location": "song109.html"
}, {
    "name": "song134",
    "location": "song134.html"
}, {
    "name": "song110",
    "location": "song110.html"
}, {
    "name": "song135",
    "location": "song135.html"
}, {
    "name": "song101",
    "location": "song101.html"
}, {
    "name": "song112",
    "location": "song112.html"
}, {
    "name": "song102",
    "location": "song102.html"
}, {
    "name": "song113",
    "location": "song113.html"
}, {
    "name": "song103",
    "location": "song103.html"
}, {
    "name": "song114",
    "location": "song114.html"
}];

function songList_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'songs': 'songList_songs',
        'mobilelistitem_1': 'songList_mobilelistitem_1',
        'mobilelistitembutton_4': 'songList_mobilelistitembutton_4',
        'mobilelistitem_2': 'songList_mobilelistitem_2',
        'mobilelistitembutton_6': 'songList_mobilelistitembutton_6',
        'mobilelistitem_3': 'songList_mobilelistitem_3',
        'mobilelistitembutton_8': 'songList_mobilelistitembutton_8',
        'mobilelistitem_4': 'songList_mobilelistitem_4',
        'mobilelistitembutton_16': 'songList_mobilelistitembutton_16',
        'mobilelistitem_5': 'songList_mobilelistitem_5',
        'mobilelistitembutton_18': 'songList_mobilelistitembutton_18',
        'mobilelistitem_6': 'songList_mobilelistitem_6',
        'mobilelistitembutton_20': 'songList_mobilelistitembutton_20',
        'mobilelistitem_7': 'songList_mobilelistitem_7',
        'mobilelistitembutton_22': 'songList_mobilelistitembutton_22',
        'mobilelistitem_8': 'songList_mobilelistitem_8',
        'mobilelistitembutton_24': 'songList_mobilelistitembutton_24',
        'mobilelistitem_9': 'songList_mobilelistitem_9',
        'mobilelistitembutton_26': 'songList_mobilelistitembutton_26',
        'mobilelistitem_10': 'songList_mobilelistitem_10',
        'mobilelistitembutton_28': 'songList_mobilelistitembutton_28',
        'mobilelistitem_11': 'songList_mobilelistitem_11',
        'mobilelistitembutton_30': 'songList_mobilelistitembutton_30',
        'mobilelistitem_12': 'songList_mobilelistitem_12',
        'mobilelistitembutton_32': 'songList_mobilelistitembutton_32',
        'mobilelistitem_13': 'songList_mobilelistitem_13',
        'mobilelistitembutton_34': 'songList_mobilelistitembutton_34',
        'mobilelistitem_14': 'songList_mobilelistitem_14',
        'mobilelistitembutton_36': 'songList_mobilelistitembutton_36',
        'mobilelistitem_15': 'songList_mobilelistitem_15',
        'mobilelistitembutton_38': 'songList_mobilelistitembutton_38',
        'mobilelistitem_16': 'songList_mobilelistitem_16',
        'mobilelistitembutton_40': 'songList_mobilelistitembutton_40',
        'mobilelistitem_17': 'songList_mobilelistitem_17',
        'mobilelistitembutton_42': 'songList_mobilelistitembutton_42',
        'mobilelistitem_18': 'songList_mobilelistitem_18',
        'mobilelistitembutton_44': 'songList_mobilelistitembutton_44',
        'mobilelistitem_19': 'songList_mobilelistitem_19',
        'mobilelistitembutton_46': 'songList_mobilelistitembutton_46',
        'mobilelistitem_20': 'songList_mobilelistitem_20',
        'mobilelistitembutton_48': 'songList_mobilelistitembutton_48',
        'mobilelistitem_21': 'songList_mobilelistitem_21',
        'mobilelistitembutton_55': 'songList_mobilelistitembutton_55',
        'mobilelistitem_22': 'songList_mobilelistitem_22',
        'mobilelistitembutton_57': 'songList_mobilelistitembutton_57',
        'mobilelistitem_23': 'songList_mobilelistitem_23',
        'mobilelistitembutton_59': 'songList_mobilelistitembutton_59',
        'mobilelistitem_24': 'songList_mobilelistitem_24',
        'mobilelistitembutton_61': 'songList_mobilelistitembutton_61',
        'mobilelistitem_25': 'songList_mobilelistitem_25',
        'mobilelistitembutton_63': 'songList_mobilelistitembutton_63',
        'mobilelistitem_26': 'songList_mobilelistitem_26',
        'mobilelistitembutton_65': 'songList_mobilelistitembutton_65',
        'mobilelistitem_27': 'songList_mobilelistitem_27',
        'mobilelistitembutton_67': 'songList_mobilelistitembutton_67',
        'mobilelistitem_28': 'songList_mobilelistitem_28',
        'mobilelistitembutton_69': 'songList_mobilelistitembutton_69',
        'mobilelistitem_29': 'songList_mobilelistitem_29',
        'mobilelistitembutton_71': 'songList_mobilelistitembutton_71',
        'mobilelistitem_30': 'songList_mobilelistitem_30',
        'mobilelistitembutton_73': 'songList_mobilelistitembutton_73',
        'mobilelistitem_31': 'songList_mobilelistitem_31',
        'mobilelistitembutton_75': 'songList_mobilelistitembutton_75',
        'mobilelistitem_32': 'songList_mobilelistitem_32',
        'mobilelistitembutton_77': 'songList_mobilelistitembutton_77',
        'mobilelistitem_33': 'songList_mobilelistitem_33',
        'mobilelistitembutton_79': 'songList_mobilelistitembutton_79',
        'mobilelistitem_34': 'songList_mobilelistitem_34',
        'mobilelistitembutton_81': 'songList_mobilelistitembutton_81',
        'mobilelistitem_35': 'songList_mobilelistitem_35',
        'mobilelistitembutton_83': 'songList_mobilelistitembutton_83',
        'mobilelistitem_36': 'songList_mobilelistitem_36',
        'mobilelistitembutton_85': 'songList_mobilelistitembutton_85',
        'mobilelistitem_37': 'songList_mobilelistitem_37',
        'mobilelistitembutton_87': 'songList_mobilelistitembutton_87',
        'mobilelistitem_38': 'songList_mobilelistitem_38',
        'mobilelistitembutton_89': 'songList_mobilelistitembutton_89',
        'mobilelistitem_39': 'songList_mobilelistitem_39',
        'mobilelistitembutton_91': 'songList_mobilelistitembutton_91',
        'mobilelistitem_40': 'songList_mobilelistitem_40',
        'mobilelistitembutton_93': 'songList_mobilelistitembutton_93',
        'mobilelistitem_41': 'songList_mobilelistitem_41',
        'mobilelistitembutton_95': 'songList_mobilelistitembutton_95',
        'mobilelistitem_42': 'songList_mobilelistitem_42',
        'mobilelistitembutton_97': 'songList_mobilelistitembutton_97',
        'mobilelistitem_43': 'songList_mobilelistitem_43',
        'mobilelistitembutton_99': 'songList_mobilelistitembutton_99',
        'mobilelistitem_44': 'songList_mobilelistitem_44',
        'mobilelistitembutton_101': 'songList_mobilelistitembutton_101',
        'mobilelistitem_45': 'songList_mobilelistitem_45',
        'mobilelistitembutton_103': 'songList_mobilelistitembutton_103',
        'mobilelistitem_46': 'songList_mobilelistitem_46',
        'mobilelistitembutton_105': 'songList_mobilelistitembutton_105',
        'mobilelistitem_47': 'songList_mobilelistitem_47',
        'mobilelistitembutton_107': 'songList_mobilelistitembutton_107',
        'mobilelistitem_48': 'songList_mobilelistitem_48',
        'mobilelistitembutton_109': 'songList_mobilelistitembutton_109',
        'mobilelistitem_49': 'songList_mobilelistitem_49',
        'mobilelistitembutton_111': 'songList_mobilelistitembutton_111',
        'mobilelistitem_50': 'songList_mobilelistitem_50',
        'mobilelistitembutton_113': 'songList_mobilelistitembutton_113',
        'mobilelistitem_51': 'songList_mobilelistitem_51',
        'mobilelistitembutton_115': 'songList_mobilelistitembutton_115',
        'mobilelistitem_52': 'songList_mobilelistitem_52',
        'mobilelistitembutton_117': 'songList_mobilelistitembutton_117',
        'mobilelistitem_53': 'songList_mobilelistitem_53',
        'mobilelistitembutton_119': 'songList_mobilelistitembutton_119',
        'mobilelistitem_54': 'songList_mobilelistitem_54',
        'mobilelistitembutton_121': 'songList_mobilelistitembutton_121',
        'mobilelistitem_55': 'songList_mobilelistitem_55',
        'mobilelistitembutton_123': 'songList_mobilelistitembutton_123',
        'mobilelistitem_56': 'songList_mobilelistitem_56',
        'mobilelistitembutton_125': 'songList_mobilelistitembutton_125',
        'mobilelistitem_57': 'songList_mobilelistitem_57',
        'mobilelistitembutton_127': 'songList_mobilelistitembutton_127',
        'mobilelistitem_58': 'songList_mobilelistitem_58',
        'mobilelistitembutton_129': 'songList_mobilelistitembutton_129',
        'mobilelistitem_59': 'songList_mobilelistitem_59',
        'mobilelistitembutton_131': 'songList_mobilelistitembutton_131',
        'mobilelistitem_60': 'songList_mobilelistitem_60',
        'mobilelistitembutton_133': 'songList_mobilelistitembutton_133',
        'mobilelistitem_61': 'songList_mobilelistitem_61',
        'mobilelistitembutton_135': 'songList_mobilelistitembutton_135',
        'mobilelistitem_62': 'songList_mobilelistitem_62',
        'mobilelistitembutton_137': 'songList_mobilelistitembutton_137',
        'mobilelistitem_63': 'songList_mobilelistitem_63',
        'mobilelistitembutton_139': 'songList_mobilelistitembutton_139',
        'mobilelistitem_64': 'songList_mobilelistitem_64',
        'mobilelistitembutton_141': 'songList_mobilelistitembutton_141',
        'mobilelistitem_65': 'songList_mobilelistitem_65',
        'mobilelistitembutton_143': 'songList_mobilelistitembutton_143',
        'mobilelistitem_66': 'songList_mobilelistitem_66',
        'mobilelistitembutton_145': 'songList_mobilelistitembutton_145',
        'mobilelistitem_67': 'songList_mobilelistitem_67',
        'mobilelistitembutton_147': 'songList_mobilelistitembutton_147',
        'mobilelistitem_68': 'songList_mobilelistitem_68',
        'mobilelistitembutton_149': 'songList_mobilelistitembutton_149',
        'mobilelistitem_69': 'songList_mobilelistitem_69',
        'mobilelistitembutton_151': 'songList_mobilelistitembutton_151',
        'mobilelistitem_70': 'songList_mobilelistitem_70',
        'mobilelistitembutton_153': 'songList_mobilelistitembutton_153',
        'mobilelistitem_71': 'songList_mobilelistitem_71',
        'mobilelistitembutton_155': 'songList_mobilelistitembutton_155',
        'mobilelistitem_72': 'songList_mobilelistitem_72',
        'mobilelistitembutton_157': 'songList_mobilelistitembutton_157',
        'mobilelistitem_73': 'songList_mobilelistitem_73',
        'mobilelistitembutton_159': 'songList_mobilelistitembutton_159',
        'mobilelistitem_74': 'songList_mobilelistitem_74',
        'mobilelistitembutton_161': 'songList_mobilelistitembutton_161',
        'mobilelistitem_75': 'songList_mobilelistitem_75',
        'mobilelistitembutton_163': 'songList_mobilelistitembutton_163',
        'mobilelistitem_76': 'songList_mobilelistitem_76',
        'mobilelistitembutton_165': 'songList_mobilelistitembutton_165',
        'mobilelistitem_77': 'songList_mobilelistitem_77',
        'mobilelistitembutton_167': 'songList_mobilelistitembutton_167',
        'mobilelistitem_78': 'songList_mobilelistitem_78',
        'mobilelistitembutton_169': 'songList_mobilelistitembutton_169',
        'mobilelistitem_79': 'songList_mobilelistitem_79',
        'mobilelistitembutton_171': 'songList_mobilelistitembutton_171',
        'mobilelistitem_80': 'songList_mobilelistitem_80',
        'mobilelistitembutton_173': 'songList_mobilelistitembutton_173',
        'mobilelistitem_81': 'songList_mobilelistitem_81',
        'mobilelistitembutton_175': 'songList_mobilelistitembutton_175',
        'mobilelistitem_82': 'songList_mobilelistitem_82',
        'mobilelistitembutton_177': 'songList_mobilelistitembutton_177',
        'mobilelistitem_83': 'songList_mobilelistitem_83',
        'mobilelistitembutton_179': 'songList_mobilelistitembutton_179',
        'mobilelistitem_84': 'songList_mobilelistitem_84',
        'mobilelistitembutton_181': 'songList_mobilelistitembutton_181',
        'mobilelistitem_85': 'songList_mobilelistitem_85',
        'mobilelistitembutton_183': 'songList_mobilelistitembutton_183',
        'mobilelistitem_86': 'songList_mobilelistitem_86',
        'mobilelistitembutton_185': 'songList_mobilelistitembutton_185',
        'mobilelistitem_87': 'songList_mobilelistitem_87',
        'mobilelistitembutton_187': 'songList_mobilelistitembutton_187',
        'mobilelistitem_88': 'songList_mobilelistitem_88',
        'mobilelistitembutton_189': 'songList_mobilelistitembutton_189',
        'mobilelistitem_89': 'songList_mobilelistitem_89',
        'mobilelistitembutton_191': 'songList_mobilelistitembutton_191',
        'mobilelistitem_90': 'songList_mobilelistitem_90',
        'mobilelistitembutton_193': 'songList_mobilelistitembutton_193',
        'mobilelistitem_91': 'songList_mobilelistitem_91',
        'mobilelistitembutton_195': 'songList_mobilelistitembutton_195',
        'mobilelistitem_92': 'songList_mobilelistitem_92',
        'mobilelistitembutton_197': 'songList_mobilelistitembutton_197',
        'mobilelistitem_93': 'songList_mobilelistitem_93',
        'mobilelistitembutton_199': 'songList_mobilelistitembutton_199',
        'mobilelistitem_94': 'songList_mobilelistitem_94',
        'mobilelistitembutton_201': 'songList_mobilelistitembutton_201',
        'mobilelistitem_95': 'songList_mobilelistitem_95',
        'mobilelistitembutton_203': 'songList_mobilelistitembutton_203',
        'mobilelistitem_96': 'songList_mobilelistitem_96',
        'mobilelistitembutton_205': 'songList_mobilelistitembutton_205',
        'mobilelistitem_97': 'songList_mobilelistitem_97',
        'mobilelistitembutton_207': 'songList_mobilelistitembutton_207',
        'mobilelistitem_98': 'songList_mobilelistitem_98',
        'mobilelistitembutton_209': 'songList_mobilelistitembutton_209',
        'mobilelistitem_99': 'songList_mobilelistitem_99',
        'mobilelistitembutton_211': 'songList_mobilelistitembutton_211',
        'mobilelistitem_100': 'songList_mobilelistitem_100',
        'mobilelistitembutton_213': 'songList_mobilelistitembutton_213',
        'mobilelistitem_101': 'songList_mobilelistitem_101',
        'mobilelistitembutton_215': 'songList_mobilelistitembutton_215',
        'mobilelistitem_102': 'songList_mobilelistitem_102',
        'mobilelistitembutton_217': 'songList_mobilelistitembutton_217',
        'mobilelistitem_103': 'songList_mobilelistitem_103',
        'mobilelistitembutton_219': 'songList_mobilelistitembutton_219',
        'mobilelistitem_104': 'songList_mobilelistitem_104',
        'mobilelistitembutton_221': 'songList_mobilelistitembutton_221',
        'mobilelistitem_105': 'songList_mobilelistitem_105',
        'mobilelistitembutton_223': 'songList_mobilelistitembutton_223',
        'mobilelistitem_106': 'songList_mobilelistitem_106',
        'mobilelistitembutton_225': 'songList_mobilelistitembutton_225',
        'mobilelistitem_107': 'songList_mobilelistitem_107',
        'mobilelistitembutton_227': 'songList_mobilelistitembutton_227',
        'mobilelistitem_108': 'songList_mobilelistitem_108',
        'mobilelistitembutton_229': 'songList_mobilelistitembutton_229',
        'mobilelistitem_109': 'songList_mobilelistitem_109',
        'mobilelistitembutton_231': 'songList_mobilelistitembutton_231',
        'mobilelistitem_110': 'songList_mobilelistitem_110',
        'mobilelistitembutton_233': 'songList_mobilelistitembutton_233',
        'mobilelistitem_111': 'songList_mobilelistitem_111',
        'mobilelistitembutton_235': 'songList_mobilelistitembutton_235',
        'mobilelistitem_112': 'songList_mobilelistitem_112',
        'mobilelistitembutton_237': 'songList_mobilelistitembutton_237',
        'mobilelistitem_113': 'songList_mobilelistitem_113',
        'mobilelistitembutton_239': 'songList_mobilelistitembutton_239',
        'mobilelistitem_114': 'songList_mobilelistitem_114',
        'mobilelistitembutton_241': 'songList_mobilelistitembutton_241',
        'mobilelistitem_115': 'songList_mobilelistitem_115',
        'mobilelistitembutton_243': 'songList_mobilelistitembutton_243',
        'mobilelistitem_116': 'songList_mobilelistitem_116',
        'mobilelistitembutton_245': 'songList_mobilelistitembutton_245',
        'mobilelistitem_117': 'songList_mobilelistitem_117',
        'mobilelistitembutton_247': 'songList_mobilelistitembutton_247',
        'mobilelistitem_118': 'songList_mobilelistitem_118',
        'mobilelistitembutton_249': 'songList_mobilelistitembutton_249',
        'mobilelistitem_119': 'songList_mobilelistitem_119',
        'mobilelistitembutton_251': 'songList_mobilelistitembutton_251',
        'mobilelistitem_120': 'songList_mobilelistitem_120',
        'mobilelistitembutton_253': 'songList_mobilelistitembutton_253',
        'mobilelistitem_121': 'songList_mobilelistitem_121',
        'mobilelistitembutton_255': 'songList_mobilelistitembutton_255',
        'mobilelistitem_122': 'songList_mobilelistitem_122',
        'mobilelistitembutton_257': 'songList_mobilelistitembutton_257',
        'mobilelistitem_123': 'songList_mobilelistitem_123',
        'mobilelistitembutton_259': 'songList_mobilelistitembutton_259',
        'mobilelistitem_124': 'songList_mobilelistitem_124',
        'mobilelistitembutton_261': 'songList_mobilelistitembutton_261',
        'mobilelistitem_125': 'songList_mobilelistitem_125',
        'mobilelistitembutton_263': 'songList_mobilelistitembutton_263',
        'mobilelistitem_126': 'songList_mobilelistitem_126',
        'mobilelistitembutton_265': 'songList_mobilelistitembutton_265',
        'mobilelistitem_127': 'songList_mobilelistitem_127',
        'mobilelistitembutton_267': 'songList_mobilelistitembutton_267',
        'mobilelistitem_128': 'songList_mobilelistitem_128',
        'mobilelistitembutton_269': 'songList_mobilelistitembutton_269',
        'mobilelistitem_129': 'songList_mobilelistitem_129',
        'mobilelistitembutton_271': 'songList_mobilelistitembutton_271',
        'mobilelistitem_130': 'songList_mobilelistitem_130',
        'mobilelistitembutton_273': 'songList_mobilelistitembutton_273',
        'mobilelistitem_131': 'songList_mobilelistitem_131',
        'mobilelistitembutton_275': 'songList_mobilelistitembutton_275',
        'mobilelistitem_132': 'songList_mobilelistitem_132',
        'mobilelistitembutton_277': 'songList_mobilelistitembutton_277',
        'mobilelistitem_133': 'songList_mobilelistitem_133',
        'mobilelistitembutton_279': 'songList_mobilelistitembutton_279',
        'mobilelistitem_134': 'songList_mobilelistitem_134',
        'mobilelistitembutton_281': 'songList_mobilelistitembutton_281',
        'mobilelistitem_135': 'songList_mobilelistitem_135',
        'mobilelistitembutton_283': 'songList_mobilelistitembutton_283',
        'mobilelistitem_136': 'songList_mobilelistitem_136',
        'mobilelistitembutton_285': 'songList_mobilelistitembutton_285',
        'mobilelistitem_137': 'songList_mobilelistitem_137',
        'mobilelistitembutton_287': 'songList_mobilelistitembutton_287',
        'mobilelistitem_138': 'songList_mobilelistitem_138',
        'mobilelistitembutton_289': 'songList_mobilelistitembutton_289'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'songList';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var songList_onLoad = function() {
        songList_elementsExtraJS();
        songList_deviceEvents();
        songList_windowEvents();
        songList_elementsEvents();
    };
    // screen window events
    function songList_windowEvents() {
        $('#songList').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function songList_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function songList_elementsExtraJS() {
        // screen (songList) extra code
        /* songs */
        listView = $("#songList_songs");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#songList_songs .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
        /* mobilelistitem_1 */
        /* mobilelistitem_2 */
        /* mobilelistitem_3 */
        /* mobilelistitem_4 */
        /* mobilelistitem_5 */
        /* mobilelistitem_6 */
        /* mobilelistitem_7 */
        /* mobilelistitem_8 */
        /* mobilelistitem_9 */
        /* mobilelistitem_10 */
        /* mobilelistitem_11 */
        /* mobilelistitem_12 */
        /* mobilelistitem_13 */
        /* mobilelistitem_14 */
        /* mobilelistitem_15 */
        /* mobilelistitem_16 */
        /* mobilelistitem_17 */
        /* mobilelistitem_18 */
        /* mobilelistitem_19 */
        /* mobilelistitem_20 */
        /* mobilelistitem_21 */
        /* mobilelistitem_22 */
        /* mobilelistitem_23 */
        /* mobilelistitem_24 */
        /* mobilelistitem_25 */
        /* mobilelistitem_26 */
        /* mobilelistitem_27 */
        /* mobilelistitem_28 */
        /* mobilelistitem_29 */
        /* mobilelistitem_30 */
        /* mobilelistitem_31 */
        /* mobilelistitem_32 */
        /* mobilelistitem_33 */
        /* mobilelistitem_34 */
        /* mobilelistitem_35 */
        /* mobilelistitem_36 */
        /* mobilelistitem_37 */
        /* mobilelistitem_38 */
        /* mobilelistitem_39 */
        /* mobilelistitem_40 */
        /* mobilelistitem_41 */
        /* mobilelistitem_42 */
        /* mobilelistitem_43 */
        /* mobilelistitem_44 */
        /* mobilelistitem_45 */
        /* mobilelistitem_46 */
        /* mobilelistitem_47 */
        /* mobilelistitem_48 */
        /* mobilelistitem_49 */
        /* mobilelistitem_50 */
        /* mobilelistitem_51 */
        /* mobilelistitem_52 */
        /* mobilelistitem_53 */
        /* mobilelistitem_54 */
        /* mobilelistitem_55 */
        /* mobilelistitem_56 */
        /* mobilelistitem_57 */
        /* mobilelistitem_58 */
        /* mobilelistitem_59 */
        /* mobilelistitem_60 */
        /* mobilelistitem_61 */
        /* mobilelistitem_62 */
        /* mobilelistitem_63 */
        /* mobilelistitem_64 */
        /* mobilelistitem_65 */
        /* mobilelistitem_66 */
        /* mobilelistitem_67 */
        /* mobilelistitem_68 */
        /* mobilelistitem_69 */
        /* mobilelistitem_70 */
        /* mobilelistitem_71 */
        /* mobilelistitem_72 */
        /* mobilelistitem_73 */
        /* mobilelistitem_74 */
        /* mobilelistitem_75 */
        /* mobilelistitem_76 */
        /* mobilelistitem_77 */
        /* mobilelistitem_78 */
        /* mobilelistitem_79 */
        /* mobilelistitem_80 */
        /* mobilelistitem_81 */
        /* mobilelistitem_82 */
        /* mobilelistitem_83 */
        /* mobilelistitem_84 */
        /* mobilelistitem_85 */
        /* mobilelistitem_86 */
        /* mobilelistitem_87 */
        /* mobilelistitem_88 */
        /* mobilelistitem_89 */
        /* mobilelistitem_90 */
        /* mobilelistitem_91 */
        /* mobilelistitem_92 */
        /* mobilelistitem_93 */
        /* mobilelistitem_94 */
        /* mobilelistitem_95 */
        /* mobilelistitem_96 */
        /* mobilelistitem_97 */
        /* mobilelistitem_98 */
        /* mobilelistitem_99 */
        /* mobilelistitem_100 */
        /* mobilelistitem_101 */
        /* mobilelistitem_102 */
        /* mobilelistitem_103 */
        /* mobilelistitem_104 */
        /* mobilelistitem_105 */
        /* mobilelistitem_106 */
        /* mobilelistitem_107 */
        /* mobilelistitem_108 */
        /* mobilelistitem_109 */
        /* mobilelistitem_110 */
        /* mobilelistitem_111 */
        /* mobilelistitem_112 */
        /* mobilelistitem_113 */
        /* mobilelistitem_114 */
        /* mobilelistitem_115 */
        /* mobilelistitem_116 */
        /* mobilelistitem_117 */
        /* mobilelistitem_118 */
        /* mobilelistitem_119 */
        /* mobilelistitem_120 */
        /* mobilelistitem_121 */
        /* mobilelistitem_122 */
        /* mobilelistitem_123 */
        /* mobilelistitem_124 */
        /* mobilelistitem_125 */
        /* mobilelistitem_126 */
        /* mobilelistitem_127 */
        /* mobilelistitem_128 */
        /* mobilelistitem_129 */
        /* mobilelistitem_130 */
        /* mobilelistitem_131 */
        /* mobilelistitem_132 */
        /* mobilelistitem_133 */
        /* mobilelistitem_134 */
        /* mobilelistitem_135 */
        /* mobilelistitem_136 */
        /* mobilelistitem_137 */
        /* mobilelistitem_138 */
    };
    // screen elements handler
    function songList_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_1"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song1', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_1"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song2', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_2"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song3', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_3"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song4', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_4"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song5', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_5"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song6', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_6"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song7', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_7"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_8"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song8', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_8"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_9"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song9', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_9"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_10"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song10', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_10"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song11', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_11"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_12"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song12', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_12"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_13"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song13', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_13"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_14"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song14', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_14"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_15"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song15', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_15"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_16"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song16', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_16"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_17"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song17', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_17"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_18"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song18', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_18"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_19"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song19', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_19"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_20"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song20', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_20"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_21"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song21', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_21"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_22"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song22', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_22"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_23"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song23', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_23"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_24"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song24', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_24"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_25"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song25', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_25"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_26"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song26', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_26"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_27"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song27', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_27"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_28"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song28', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_28"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_29"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song29', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_29"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_30"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song30', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_30"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_31"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song31', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_31"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_32"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song32', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_32"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_33"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song33', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_33"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_34"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song34', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_34"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_35"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song35', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_35"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_36"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song36', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_36"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_37"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song37', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_37"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_38"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song38', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_38"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_39"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song39', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_39"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_40"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song40', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_40"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_41"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song41', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_41"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_42"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song42', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_42"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_43"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song43', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_43"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_44"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song44', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_44"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_45"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song45', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_45"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_46"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song46', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_46"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_47"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song47', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_47"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_48"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song48', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_48"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_49"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song49', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_49"]');
		$(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_50"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song50', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_50"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_51"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song51', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_51"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_52"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song52', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_52"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_53"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song53', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_53"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_54"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song54', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_54"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_55"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song55', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_55"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_56"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song56', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_56"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_57"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song57', {
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_57"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_58"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song58', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_58"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_59"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song59', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_59"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_60"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song60', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_60"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_61"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song61', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_61"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_62"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song62', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_62"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_63"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song63', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_63"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_64"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song64', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_64"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_65"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song65', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_65"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_66"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song66', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_66"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_67"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song67', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_67"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_68"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song68', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_68"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_69"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song69', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_69"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_70"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song70', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_70"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_71"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song71', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_71"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_72"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song72', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_72"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_73"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song73', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_73"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_74"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song74', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_74"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_75"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song75', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_75"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_76"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song76', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_76"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_77"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song77', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_77"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_78"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song78', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_78"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_79"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song79', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_79"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_80"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song80', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_80"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_81"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song81', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_81"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_82"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song82', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_82"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_83"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song83', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_83"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_84"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song84', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_84"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_85"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song85', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_85"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_86"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song86', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_86"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_87"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song87', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_87"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_88"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song88', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_88"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_89"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song89', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_89"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_90"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song90', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_90"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_91"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song91', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_91"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_92"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song92', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_92"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_93"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song93', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_93"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_94"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song94', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_94"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_95"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song95', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_95"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_96"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song96', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_96"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_97"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song97', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_97"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_98"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song98', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_98"]');
		$(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_99"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song99', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_99"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_100"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song100', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_100"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_101"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song101', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_101"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_102"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song102', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_102"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_103"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song103', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_103"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_104"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song104', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_104"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_105"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song105', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_105"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_106"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song106', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_106"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_107"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song107', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_107"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_108"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song108', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_108"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_109"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song109', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_109"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_110"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song110', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_110"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_111"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song111', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_111"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_112"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song112', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_112"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_113"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song113', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_113"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_114"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song114', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_114"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_115"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song115', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_115"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_116"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song116', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_116"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_117"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song117', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_117"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_118"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song118', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_118"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_119"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song119', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_119"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_120"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song120', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_120"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_121"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song121', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_121"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_122"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song122', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_122"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_123"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song123', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_123"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_124"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song124', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_124"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_125"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song125', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_125"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_126"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song126', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_126"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_127"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song127', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_127"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_128"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song128', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_128"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_129"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song129', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_129"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_130"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song130', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_130"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_131"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song131', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_131"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_132"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song132', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_132"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_133"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song133', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_133"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_134"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song134', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_134"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_135"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song135', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_135"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_136"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song136', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_136"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_137"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song137', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_137"]');
        $(document).off("click", '#songList_mobilecontainer [name="mobilelistitem_138"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('song138', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#songList_mobilecontainer [name="mobilelistitem_138"]');
    };
    $(document).off("pagebeforeshow", "#songList").on("pagebeforeshow", "#songList", function(event, ui) {
        Apperyio.CurrentScreen = "songList";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    songList_onLoad();
};
$(document).off("pagecreate", "#songList").on("pagecreate", "#songList", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    songList_js();
});