/*
 * JS for song3 generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '0c2b18ad-30dc-4103-ae45-9fdf77d705b4';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "song18",
    "location": "song18.html"
}, {
    "name": "song19",
    "location": "song19.html"
}, {
    "name": "song3",
    "location": "song3.html"
}, {
    "name": "song20",
    "location": "song20.html"
}, {
    "name": "song4",
    "location": "song4.html"
}, {
    "name": "song5",
    "location": "song5.html"
}, {
    "name": "song6",
    "location": "song6.html"
}, {
    "name": "song36",
    "location": "song36.html"
}, {
    "name": "song2",
    "location": "song2.html"
}, {
    "name": "song16",
    "location": "song16.html"
}, {
    "name": "song38",
    "location": "song38.html"
}, {
    "name": "song39",
    "location": "song39.html"
}, {
    "name": "song17",
    "location": "song17.html"
}, {
    "name": "song40",
    "location": "song40.html"
}, {
    "name": "songList",
    "location": "songList.html"
}, {
    "name": "song15",
    "location": "song15.html"
}, {
    "name": "song32",
    "location": "song32.html"
}, {
    "name": "song33",
    "location": "song33.html"
}, {
    "name": "song34",
    "location": "song34.html"
}, {
    "name": "song35",
    "location": "song35.html"
}, {
    "name": "song49",
    "location": "song49.html"
}, {
    "name": "song14",
    "location": "song14.html"
}, {
    "name": "song12",
    "location": "song12.html"
}, {
    "name": "song27",
    "location": "song27.html"
}, {
    "name": "song28",
    "location": "song28.html"
}, {
    "name": "song29",
    "location": "song29.html"
}, {
    "name": "song30",
    "location": "song30.html"
}, {
    "name": "song13",
    "location": "song13.html"
}, {
    "name": "song47",
    "location": "song47.html"
}, {
    "name": "song48",
    "location": "song48.html"
}, {
    "name": "song31",
    "location": "song31.html"
}, {
    "name": "song45",
    "location": "song45.html"
}, {
    "name": "song22",
    "location": "song22.html"
}, {
    "name": "song23",
    "location": "song23.html"
}, {
    "name": "song9",
    "location": "song9.html"
}, {
    "name": "song10",
    "location": "song10.html"
}, {
    "name": "song11",
    "location": "song11.html"
}, {
    "name": "song24",
    "location": "song24.html"
}, {
    "name": "song25",
    "location": "song25.html"
}, {
    "name": "song46",
    "location": "song46.html"
}, {
    "name": "song26",
    "location": "song26.html"
}, {
    "name": "song21",
    "location": "song21.html"
}, {
    "name": "song37",
    "location": "song37.html"
}, {
    "name": "song1",
    "location": "song1.html"
}, {
    "name": "song43",
    "location": "song43.html"
}, {
    "name": "song44",
    "location": "song44.html"
}, {
    "name": "song8",
    "location": "song8.html"
}, {
    "name": "song7",
    "location": "song7.html"
}, {
    "name": "song41",
    "location": "song41.html"
}, {
    "name": "song42",
    "location": "song42.html"
}, {
    "name": "song50",
    "location": "song50.html"
}, {
    "name": "song51",
    "location": "song51.html"
}, {
    "name": "song68",
    "location": "song68.html"
}, {
    "name": "song62",
    "location": "song62.html"
}, {
    "name": "song63",
    "location": "song63.html"
}, {
    "name": "song64",
    "location": "song64.html"
}, {
    "name": "song65",
    "location": "song65.html"
}, {
    "name": "song66",
    "location": "song66.html"
}, {
    "name": "song67",
    "location": "song67.html"
}, {
    "name": "song79",
    "location": "song79.html"
}, {
    "name": "song80",
    "location": "song80.html"
}, {
    "name": "song82",
    "location": "song82.html"
}, {
    "name": "song83",
    "location": "song83.html"
}, {
    "name": "song84",
    "location": "song84.html"
}, {
    "name": "song85",
    "location": "song85.html"
}, {
    "name": "song86",
    "location": "song86.html"
}, {
    "name": "song60",
    "location": "song60.html"
}, {
    "name": "song87",
    "location": "song87.html"
}, {
    "name": "song88",
    "location": "song88.html"
}, {
    "name": "song61",
    "location": "song61.html"
}, {
    "name": "song89",
    "location": "song89.html"
}, {
    "name": "song90",
    "location": "song90.html"
}, {
    "name": "song91",
    "location": "song91.html"
}, {
    "name": "song92",
    "location": "song92.html"
}, {
    "name": "song93",
    "location": "song93.html"
}, {
    "name": "song94",
    "location": "song94.html"
}, {
    "name": "song95",
    "location": "song95.html"
}, {
    "name": "song96",
    "location": "song96.html"
}, {
    "name": "song97",
    "location": "song97.html"
}, {
    "name": "song98",
    "location": "song98.html"
}, {
    "name": "song71",
    "location": "song71.html"
}, {
    "name": "song72",
    "location": "song72.html"
}, {
    "name": "song73",
    "location": "song73.html"
}, {
    "name": "song74",
    "location": "song74.html"
}, {
    "name": "song58",
    "location": "song58.html"
}, {
    "name": "song75",
    "location": "song75.html"
}, {
    "name": "song59",
    "location": "song59.html"
}, {
    "name": "song76",
    "location": "song76.html"
}, {
    "name": "song77",
    "location": "song77.html"
}, {
    "name": "song78",
    "location": "song78.html"
}, {
    "name": "song56",
    "location": "song56.html"
}, {
    "name": "song57",
    "location": "song57.html"
}, {
    "name": "song70",
    "location": "song70.html"
}, {
    "name": "song81",
    "location": "song81.html"
}, {
    "name": "song69",
    "location": "song69.html"
}, {
    "name": "song52",
    "location": "song52.html"
}, {
    "name": "song53",
    "location": "song53.html"
}, {
    "name": "song54",
    "location": "song54.html"
}, {
    "name": "song55",
    "location": "song55.html"
}, {
    "name": "song136",
    "location": "song136.html"
}, {
    "name": "song99",
    "location": "song99.html"
}, {
    "name": "song115",
    "location": "song115.html"
}, {
    "name": "song104",
    "location": "song104.html"
}, {
    "name": "song105",
    "location": "song105.html"
}, {
    "name": "song116",
    "location": "song116.html"
}, {
    "name": "song117",
    "location": "song117.html"
}, {
    "name": "song106",
    "location": "song106.html"
}, {
    "name": "song107",
    "location": "song107.html"
}, {
    "name": "song118",
    "location": "song118.html"
}, {
    "name": "song108",
    "location": "song108.html"
}, {
    "name": "song119",
    "location": "song119.html"
}, {
    "name": "song120",
    "location": "song120.html"
}, {
    "name": "song121",
    "location": "song121.html"
}, {
    "name": "song123",
    "location": "song123.html"
}, {
    "name": "song124",
    "location": "song124.html"
}, {
    "name": "song137",
    "location": "song137.html"
}, {
    "name": "song125",
    "location": "song125.html"
}, {
    "name": "song138",
    "location": "song138.html"
}, {
    "name": "song126",
    "location": "song126.html"
}, {
    "name": "song127",
    "location": "song127.html"
}, {
    "name": "song128",
    "location": "song128.html"
}, {
    "name": "song129",
    "location": "song129.html"
}, {
    "name": "song100",
    "location": "song100.html"
}, {
    "name": "song111",
    "location": "song111.html"
}, {
    "name": "song122",
    "location": "song122.html"
}, {
    "name": "song130",
    "location": "song130.html"
}, {
    "name": "song131",
    "location": "song131.html"
}, {
    "name": "song132",
    "location": "song132.html"
}, {
    "name": "song133",
    "location": "song133.html"
}, {
    "name": "song109",
    "location": "song109.html"
}, {
    "name": "song134",
    "location": "song134.html"
}, {
    "name": "song110",
    "location": "song110.html"
}, {
    "name": "song135",
    "location": "song135.html"
}, {
    "name": "song101",
    "location": "song101.html"
}, {
    "name": "song112",
    "location": "song112.html"
}, {
    "name": "song102",
    "location": "song102.html"
}, {
    "name": "song113",
    "location": "song113.html"
}, {
    "name": "song103",
    "location": "song103.html"
}, {
    "name": "song114",
    "location": "song114.html"
}];

function song3_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'html_5': 'song3_html_5'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'song3';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var song3_onLoad = function() {
        song3_elementsExtraJS();
        song3_deviceEvents();
        song3_windowEvents();
        song3_elementsEvents();
    };
    // screen window events
    function song3_windowEvents() {
        $('#song3').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function song3_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function song3_elementsExtraJS() {
        // screen (song3) extra code
    };
    // screen elements handler
    function song3_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#song3").on("pagebeforeshow", "#song3", function(event, ui) {
        Apperyio.CurrentScreen = "song3";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    song3_onLoad();
};
$(document).off("pagecreate", "#song3").on("pagecreate", "#song3", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    song3_js();
});